import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>VK codes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-auto text-center">
        <h1 className="text-6xl font-semibold">
          Welcome to{" "}
          <a
            className="text-blue-500 hover:underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className="text-lg bg-gray-50 px-1 py-1 font-mono">
            pages/index.js
          </code>
        </p>

        <div className="m-auto w-2/4 grid md:grid-cols-2 place-content-center place-items-stretch gap-3">
          <a
            href="https://nextjs.org/docs"
            className="group flex flex-col items-center px-5 border border-gray-100 text-center rounded-lg hover:border-blue-500"
          >
            <h2 className="text-left text-2xl mx-2 my-4 group-hover:text-blue-500">
              Documentation &rarr;
            </h2>
            <p className="text-left text-xl mx-2 my-4 max-w-xs group-hover:text-blue-500">
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a
            className="group flex flex-col items-center px-5  border border-gray-100 text-center rounded-lg hover:border-blue-500"
            href="https://nextjs.org/learn"
          >
            <h2 className="text-left text-2xl mx-2 my-5 group-hover:text-blue-500">
              Learn &rarr;
            </h2>
            <p className="text-left text-xl mx-2 my-5 group-hover:text-blue-500">
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className="group flex flex-col items-center px-5 border border-gray-100 text-center rounded-lg hover:border-blue-500"
          >
            <h2 className="text-left text-2xl mx-2 my-5 group-hover:text-blue-500">
              Examples &rarr;
            </h2>
            <p className="text-left text-xl mx-2 my-5 group-hover:text-blue-500">
              Discover and deploy boilerplate example Next.js projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="group flex flex-col items-center px-5 border border-gray-100 text-center rounded-lg hover:border-blue-500"
          >
            <h2 className="text-left text-2xl mx-2 my-5 group-hover:text-blue-500">
              Deploy &rarr;
            </h2>
            <p className="text-left text-xl mx-2 my-5 group-hover:text-blue-500">
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
